export const genderOptions = [
    {
        key: "female",
        value: "female",
        label: "Female",
        content: "Female",
    },
    {
        key: "male",
        value: "male",
        label: "Male",
        content: "Male",
    },
    {
        key: "rather-not-say",
        value: "rather-not-say",
        label: "Rather not say",
        content: "Rather not say",
    },
    {
        key: "custom",
        value: "custom",
        label: "Custom",
        content: "Custom",
    },
];

export const pronounOptions = [
    {
        key: "she",
        value: "she",
        label: "She",
        content: "She: \"She/Her/Hers\"",
    },
    {
        key: "he",
        value: "he",
        label: "He",
        content: "He: \"He/Him/His\"",
    },
    {
        key: "they",
        value: "they",
        label: "They",
        content: "They: \"They/Them/Theirs\"",
    },
];

export const palateOptions = [
    {
        key: "east-asian",
        label: "East Asian",
        children: [
            { key: "japanese", label: "Japanese" },
            { key: "korean", label: "Korean" },
            { key: "chinese", label: "Chinese" },
            { key: "taiwanese", label: "Taiwanese" },
        ],
    },
    {
        key: "south-asian",
        label: "South Asian",
        children: [
            { key: "nepalese", label: "Nepalese" },
            { key: "bangladesh", label: "Bangladesh" },
            { key: "sri-lankan", label: "Sri Lankan" },
            { key: "maldivian", label: "Maldivian" },
            { key: "indian", label: "Indian" },
            { key: "pakistani", label: "Pakistani" },
        ],
    },
    {
        key: "south-east-asian",
        label: "South East Asian",
        children: [
            { key: "malaysian", label: "Malaysian" },
            { key: "filipino", label: "Filipino" },
            { key: "singaporean", label: "Singaporean" },
            { key: "indonesian", label: "Indonesian" },
        ],
    },
    {
        key: "middle-eastern",
        label: "Middle Eastern",
        children: [
            { key: "armenian", label: "Armenian" },
            { key: "east-arabian", label: "East Arabian" },
            { key: "lebanese", label: "Lebanese" },
            { key: "caucasian", label: "Caucasian" },
            { key: "iranian", label: "Iranian" },
            { key: "turkish", label: "Turkish" },
        ],
    },
    {
        key: "african",
        label: "African",
        children: [
            { key: "angolan", label: "Angolan" },
            { key: "congolese", label: "Congolese" },
            { key: "ethiopian", label: "Ethiopian" },
            { key: "kenyan", label: "Kenyan" },
            { key: "zimbabwean", label: "Zimbabwean" },
            { key: "egyptian", label: "Egyptian" },
            { key: "algerian", label: "Algerian" },
            { key: "ghanaian", label: "Ghanaian" },
            { key: "nigerian", label: "Nigerian" },
        ],
    },
    {
        key: "north-american",
        label: "North American",
        children: [
            { key: "canadian", label: "Canadian" },
            { key: "mexican", label: "Mexican" },
            { key: "american", label: "American" },
        ],
    },
    {
        key: "european",
        label: "European",
        children: [
            { key: "british", label: "British" },
            { key: "spanish", label: "Spanish" },
            { key: "italian", label: "Italian" },
            { key: "french", label: "French" },
            { key: "german", label: "German" },
            { key: "russian", label: "Russian" },
            { key: "danish", label: "Danish" },
            { key: "finnish", label: "Finnish" },
            { key: "swedish", label: "Swedish" },
            { key: "romanian", label: "Romanian" },
            { key: "greek", label: "Greek" },
            { key: "portuguese", label: "Portuguese" },
        ],
    },
    {
        key: "oceanic",
        label: "Oceanic",
        children: [
            { key: "australian", label: "Australian" },
            { key: "polynesian", label: "Polynesian" },
        ],
    },
];

export const languageOptions = [
    { value: "en", label: "English" },
    { value: "fil", label: "Filipino" },
    { value: "es", label: "Spanish" },
    { value: "zh", label: "Chinese" },
    { value: "ja", label: "Japanese" },
    { value: "ko", label: "Korean" },
    { value: "fr", label: "French" },
    { value: "de", label: "German" },
    { value: "it", label: "Italian" },
    { value: "pt", label: "Portuguese" },
    { value: "ru", label: "Russian" },
    { value: "ar", label: "Arabic" },
    { value: "hi", label: "Hindi" },
    { value: "bn", label: "Bengali" },
    { value: "ur", label: "Urdu" },
    { value: "vi", label: "Vietnamese" },
    { value: "th", label: "Thai" },
    { value: "id", label: "Indonesian" },
    { value: "ms", label: "Malay" },
    { value: "tr", label: "Turkish" },
    { value: "pl", label: "Polish" },
    { value: "nl", label: "Dutch" },
    { value: "sv", label: "Swedish" },
    { value: "fi", label: "Finnish" },
    { value: "da", label: "Danish" },
    { value: "no", label: "Norwegian" },
    { value: "he", label: "Hebrew" },
    { value: "el", label: "Greek" },
    { value: "hu", label: "Hungarian" },
    { value: "cs", label: "Czech" },
    { value: "ro", label: "Romanian" },
    { value: "bg", label: "Bulgarian" },
    { value: "uk", label: "Ukrainian" },
    { value: "hr", label: "Croatian" },
    { value: "sl", label: "Slovenian" },
    { value: "lt", label: "Lithuanian" },
    { value: "lv", label: "Latvian" },
    { value: "et", label: "Estonian" },
    { value: "sr", label: "Serbian" },
    { value: "mk", label: "Macedonian" },
    { value: "sk", label: "Slovak" },
    { value: "is", label: "Icelandic" },
    { value: "mt", label: "Maltese" },
    { value: "ga", label: "Irish" },
    { value: "cy", label: "Welsh" },
    { value: "eu", label: "Basque" },
    { value: "gl", label: "Galician" },
    { value: "ca", label: "Catalan" },
    { value: "sq", label: "Albanian" },
    { value: "bs", label: "Bosnian" },
    { value: "mk", label: "Macedonian" },
    { value: "az", label: "Azerbaijani" },
    { value: "hy", label: "Armenian" },
    { value: "ka", label: "Georgian" },
    { value: "kk", label: "Kazakh" },
    { value: "uz", label: "Uzbek" },
    { value: "tg", label: "Tajik" },
    { value: "ky", label: "Kyrgyz" },
    { value: "mn", label: "Mongolian" },
    { value: "ps", label: "Pashto" },
    { value: "fa", label: "Persian" },
    { value: "sw", label: "Swahili" },
    { value: "yo", label: "Yoruba" },
    { value: "ig", label: "Igbo" },
    { value: "ha", label: "Hausa" },
    { value: "am", label: "Amharic" },
    { value: "om", label: "Oromo" },
    { value: "so", label: "Somali" },
    { value: "ti", label: "Tigrinya" },
    { value: "rw", label: "Kinyarwanda" },
    { value: "ln", label: "Lingala" },
    { value: "mg", label: "Malagasy" },
];
