export const genderOptions = [
    {
        key: "female",
        value: "female",
        label: "Female",
        content: "Female",
    },
    {
        key: "male",
        value: "male",
        label: "Male",
        content: "Male",
    },
    {
        key: "rather-not-say",
        value: "rather-not-say",
        label: "Rather not say",
        content: "Rather not say",
    },
    {
        key: "custom",
        value: "custom",
        label: "Custom",
        content: "Custom",
    },
];

export const pronounOptions = [
    {
        key: "she",
        value: "she",
        label: "She",
        content: "She: \"She/Her/Hers\"",
    },
    {
        key: "he",
        value: "he",
        label: "He",
        content: "He: \"He/Him/His\"",
    },
    {
        key: "they",
        value: "they",
        label: "They",
        content: "They: \"They/Them/Theirs\"",
    },
];

export const palateOptions = [
  {
    key: "east-asian",
    label: "East Asian",
    children: [
      { key: "japanese", label: "Japanese", flag: "https://flagcdn.com/jp.svg" },
      { key: "korean", label: "Korean", flag: "https://flagcdn.com/kr.svg" },
      { key: "chinese", label: "Chinese", flag: "https://flagcdn.com/cn.svg" },
      { key: "taiwanese", label: "Taiwanese", flag: "https://flagcdn.com/tw.svg" },
    ],
  },
  {
    key: "south-asian",
    label: "South Asian",
    children: [
      { key: "nepalese", label: "Nepalese", flag: "https://flagcdn.com/np.svg" },
      { key: "bangladesh", label: "Bangladesh", flag: "https://flagcdn.com/bd.svg" },
      { key: "sri-lankan", label: "Sri Lankan", flag: "https://flagcdn.com/lk.svg" },
      { key: "maldivian", label: "Maldivian", flag: "https://flagcdn.com/mv.svg" },
      { key: "indian", label: "Indian", flag: "https://flagcdn.com/in.svg" },
      { key: "pakistani", label: "Pakistani", flag: "https://flagcdn.com/pk.svg" },
    ],
  },
  {
    key: "south-east-asian",
    label: "South East Asian",
    children: [
      { key: "malaysian", label: "Malaysian", flag: "https://flagcdn.com/my.svg" },
      { key: "filipino", label: "Filipino", flag: "https://flagcdn.com/ph.svg" },
      { key: "singaporean", label: "Singaporean", flag: "https://flagcdn.com/sg.svg" },
      { key: "indonesian", label: "Indonesian", flag: "https://flagcdn.com/id.svg" },
    ],
  },
  {
    key: "middle-eastern",
    label: "Middle Eastern",
    children: [
      { key: "armenian", label: "Armenian", flag: "https://flagcdn.com/am.svg" },
      { key: "east-arabian", label: "East Arabian", flag: "https://flagcdn.com/sa.svg" }, // Saudi Arabia
      { key: "lebanese", label: "Lebanese", flag: "https://flagcdn.com/lb.svg" },
      { key: "caucasian", label: "Caucasian", flag: "https://flagcdn.com/ge.svg" }, // Georgia
      { key: "iranian", label: "Iranian", flag: "https://flagcdn.com/ir.svg" },
      { key: "turkish", label: "Turkish", flag: "https://flagcdn.com/tr.svg" },
    ],
  },
  {
    key: "african",
    label: "African",
    children: [
      { key: "angolan", label: "Angolan", flag: "https://flagcdn.com/ao.svg" },
      { key: "congolese", label: "Congolese", flag: "https://flagcdn.com/cd.svg" },
      { key: "ethiopian", label: "Ethiopian", flag: "https://flagcdn.com/et.svg" },
      { key: "kenyan", label: "Kenyan", flag: "https://flagcdn.com/ke.svg" },
      { key: "zimbabwean", label: "Zimbabwean", flag: "https://flagcdn.com/zw.svg" },
      { key: "egyptian", label: "Egyptian", flag: "https://flagcdn.com/eg.svg" },
      { key: "algerian", label: "Algerian", flag: "https://flagcdn.com/dz.svg" },
      { key: "ghanaian", label: "Ghanaian", flag: "https://flagcdn.com/gh.svg" },
      { key: "nigerian", label: "Nigerian", flag: "https://flagcdn.com/ng.svg" },
    ],
  },
  {
    key: "north-american",
    label: "North American",
    children: [
      { key: "canadian", label: "Canadian", flag: "https://flagcdn.com/ca.svg" },
      { key: "mexican", label: "Mexican", flag: "https://flagcdn.com/mx.svg" },
      { key: "american", label: "American", flag: "https://flagcdn.com/us.svg" },
    ],
  },
  {
    key: "european",
    label: "European",
    children: [
      { key: "british", label: "British", flag: "https://flagcdn.com/gb.svg" },
      { key: "spanish", label: "Spanish", flag: "https://flagcdn.com/es.svg" },
      { key: "italian", label: "Italian", flag: "https://flagcdn.com/it.svg" },
      { key: "french", label: "French", flag: "https://flagcdn.com/fr.svg" },
      { key: "german", label: "German", flag: "https://flagcdn.com/de.svg" },
      { key: "russian", label: "Russian", flag: "https://flagcdn.com/ru.svg" },
      { key: "danish", label: "Danish", flag: "https://flagcdn.com/dk.svg" },
      { key: "finnish", label: "Finnish", flag: "https://flagcdn.com/fi.svg" },
      { key: "swedish", label: "Swedish", flag: "https://flagcdn.com/se.svg" },
      { key: "romanian", label: "Romanian", flag: "https://flagcdn.com/ro.svg" },
      { key: "greek", label: "Greek", flag: "https://flagcdn.com/gr.svg" },
      { key: "portuguese", label: "Portuguese", flag: "https://flagcdn.com/pt.svg" },
    ],
  },
  {
    key: "oceanic",
    label: "Oceanic",
    children: [
      { key: "australian", label: "Australian", flag: "https://flagcdn.com/au.svg" },
      { key: "polynesian", label: "Polynesian", flag: "https://flagcdn.com/ck.svg" }, // Cook Islands as general Polynesia flag
    ],
  },
];

export const languageOptions = [
    { value: "en", label: "English" },
    { value: "fil", label: "Filipino" },
    { value: "es", label: "Spanish" },
    { value: "zh", label: "Chinese" },
    { value: "ja", label: "Japanese" },
    { value: "ko", label: "Korean" },
    { value: "fr", label: "French" },
    { value: "de", label: "German" },
    { value: "it", label: "Italian" },
    { value: "pt", label: "Portuguese" },
    { value: "ru", label: "Russian" },
    { value: "ar", label: "Arabic" },
    { value: "hi", label: "Hindi" },
    { value: "bn", label: "Bengali" },
    { value: "ur", label: "Urdu" },
    { value: "vi", label: "Vietnamese" },
    { value: "th", label: "Thai" },
    { value: "id", label: "Indonesian" },
    { value: "ms", label: "Malay" },
    { value: "tr", label: "Turkish" },
    { value: "pl", label: "Polish" },
    { value: "nl", label: "Dutch" },
    { value: "sv", label: "Swedish" },
    { value: "fi", label: "Finnish" },
    { value: "da", label: "Danish" },
    { value: "no", label: "Norwegian" },
    { value: "he", label: "Hebrew" },
    { value: "el", label: "Greek" },
    { value: "hu", label: "Hungarian" },
    { value: "cs", label: "Czech" },
    { value: "ro", label: "Romanian" },
    { value: "bg", label: "Bulgarian" },
    { value: "uk", label: "Ukrainian" },
    { value: "hr", label: "Croatian" },
    { value: "sl", label: "Slovenian" },
    { value: "lt", label: "Lithuanian" },
    { value: "lv", label: "Latvian" },
    { value: "et", label: "Estonian" },
    { value: "sr", label: "Serbian" },
    { value: "mk", label: "Macedonian" },
    { value: "sk", label: "Slovak" },
    { value: "is", label: "Icelandic" },
    { value: "mt", label: "Maltese" },
    { value: "ga", label: "Irish" },
    { value: "cy", label: "Welsh" },
    { value: "eu", label: "Basque" },
    { value: "gl", label: "Galician" },
    { value: "ca", label: "Catalan" },
    { value: "sq", label: "Albanian" },
    { value: "bs", label: "Bosnian" },
    { value: "mk", label: "Macedonian" },
    { value: "az", label: "Azerbaijani" },
    { value: "hy", label: "Armenian" },
    { value: "ka", label: "Georgian" },
    { value: "kk", label: "Kazakh" },
    { value: "uz", label: "Uzbek" },
    { value: "tg", label: "Tajik" },
    { value: "ky", label: "Kyrgyz" },
    { value: "mn", label: "Mongolian" },
    { value: "ps", label: "Pashto" },
    { value: "fa", label: "Persian" },
    { value: "sw", label: "Swahili" },
    { value: "yo", label: "Yoruba" },
    { value: "ig", label: "Igbo" },
    { value: "ha", label: "Hausa" },
    { value: "am", label: "Amharic" },
    { value: "om", label: "Oromo" },
    { value: "so", label: "Somali" },
    { value: "ti", label: "Tigrinya" },
    { value: "rw", label: "Kinyarwanda" },
    { value: "ln", label: "Lingala" },
    { value: "mg", label: "Malagasy" },
];
