export const HOME = "/";
export const LOGIN = "/login";
export const REGISTER = "/register";
export const ONBOARDING_ONE = "/onboarding";
export const ONBOARDING_TWO = "/onboarding"; // Now both steps use the same route
export const SETTINGS = "/settings";
export const PROFILE = "/profile";
export const PROFILE_EDIT = "/profile/edit";
export const DASHBOARD = "/dashboard";
export const DASHBOARD_LISTS = "/dashboard/lists";
export const DASHBOARD_REVIEWS = "/dashboard/reviews";
export const DASHBOARD_PROFILE = "/dashboard/profile";
export const DASHBOARD_SETTINGS = "/dashboard/settings";
export const RESTAURANTS = "/restaurants";
export const ADD_REVIEW = "/add-review"; // Deprecated: Use TASTYSTUDIO_ADD_REVIEW
export const EDIT_REVIEW = "/edit-review";
export const LISTING = "/review-listing"; // Deprecated: Use TASTYSTUDIO_REVIEW_LISTING
export const TASTYSTUDIO_DASHBOARD = "/tastystudio/dashboard";
export const TASTYSTUDIO_ADD_REVIEW = "/tastystudio/add-review";
export const TASTYSTUDIO_ADD_REVIEW_CREATE = "/tastystudio/add-review/create";
export const TASTYSTUDIO_ADD_REVIEW_SUCCESS = "/tastystudio/add-review/success";
export const TASTYSTUDIO_REVIEW_LISTING = "/tastystudio/review-listing";
export const TASTYSTUDIO_EDIT_REVIEW = "/tastystudio/edit-review";
export const LISTING_DRAFT = "/listing/draft";
export const LISTING_STEP_ONE = "/listing/step-1";
export const LISTING_EXPLANATION = "/listing/explanation";
export const HELP = "/help";
export const WRITING_GUIDELINES = "/writing-guidelines";
export const TERMS_OF_SERVICE = "/terms-of-service";
export const CONTENT_GUIDELINES = "/content-guidelines";
export const PRIVACY_POLICY = "/privacy-policy";
export const COOKIE_POLICY = "/cookie-policy";
export const REVIEWS_VIEWER = "/reviews/viewer";

export const GOOGLE_MAPS = (lat: number, lng: number) => `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`;
