export const minimumPassword = 5
export const ageLimit = 18
export const userNameMinLimit = 3 // Minimum 3 characters for username
export const userNameMaxLimit = 20
export const imageMBLimit = 5 // 5MB
export const imageSizeLimit = imageMBLimit * 1024 * 1024 // 5MB
export const aboutMeMaxLimit = 250 // Changed from 500 to 250
export const palateLimit = 2
export const maximumImage = 6
export const minimumImage = 1
export const listingTitleLimit = 30
export const reviewTitleLimit = 150
export const reviewTitleDisplayLimit = 50
export const reviewTitleMaxLimit = 50
export const reviewDescriptionLimit = 1000
export const reviewDescriptionDisplayLimit = 300
export const reviewDescriptionMaxLimit = 1200