export const palateFlagMap: Record<string, string> = {
  japanese: "https://flagcdn.com/jp.svg",
  korean: "https://flagcdn.com/kr.svg",
  chinese: "https://flagcdn.com/cn.svg",
  taiwanese: "https://flagcdn.com/tw.svg",
  nepalese: "https://flagcdn.com/np.svg",
  bangladesh: "https://flagcdn.com/bd.svg",
  "sri lankan": "https://flagcdn.com/lk.svg",
  maldivian: "https://flagcdn.com/mv.svg",
  indian: "https://flagcdn.com/in.svg",
  pakistani: "https://flagcdn.com/pk.svg",
  malaysian: "https://flagcdn.com/my.svg",
  filipino: "https://flagcdn.com/ph.svg",
  singaporean: "https://flagcdn.com/sg.svg",
  indonesian: "https://flagcdn.com/id.svg",
  armenian: "https://flagcdn.com/am.svg",
  "east arabian": "https://flagcdn.com/sa.svg",
  lebanese: "https://flagcdn.com/lb.svg",
  caucasian: "https://flagcdn.com/ge.svg",
  iranian: "https://flagcdn.com/ir.svg",
  turkish: "https://flagcdn.com/tr.svg",
  angolan: "https://flagcdn.com/ao.svg",
  congolese: "https://flagcdn.com/cd.svg",
  ethiopian: "https://flagcdn.com/et.svg",
  kenyan: "https://flagcdn.com/ke.svg",
  zimbabwean: "https://flagcdn.com/zw.svg",
  egyptian: "https://flagcdn.com/eg.svg",
  algerian: "https://flagcdn.com/dz.svg",
  ghanaian: "https://flagcdn.com/gh.svg",
  nigerian: "https://flagcdn.com/ng.svg",
  canadian: "https://flagcdn.com/ca.svg",
  mexican: "https://flagcdn.com/mx.svg",
  american: "https://flagcdn.com/us.svg",
  british: "https://flagcdn.com/gb.svg",
  spanish: "https://flagcdn.com/es.svg",
  italian: "https://flagcdn.com/it.svg",
  french: "https://flagcdn.com/fr.svg",
  german: "https://flagcdn.com/de.svg",
  russian: "https://flagcdn.com/ru.svg",
  danish: "https://flagcdn.com/dk.svg",
  finnish: "https://flagcdn.com/fi.svg",
  swedish: "https://flagcdn.com/se.svg",
  romanian: "https://flagcdn.com/ro.svg",
  greek: "https://flagcdn.com/gr.svg",
  portuguese: "https://flagcdn.com/pt.svg",
  australian: "https://flagcdn.com/au.svg",
  polynesian: "https://flagcdn.com/ck.svg",
};
